# Core Global Configuration
global:
  random_seed: 42
  max_workers: 8
  result_dir: "./results"

# Runtime Parameters
run_params:
  samples: 500
  dataset: "./data/bigvul_polars.parquet"
  iterations: 20
  algorithm: "greedy"
  run_mode: "attack"
  label_map: "./models/finetuned_model_codebert_1/label_map.json"
  use_majority_voting: false

# Target Models
model_zoo:
    CodeBERT: "./models/finetuned_model_codebert_1"

# Candidate Generation Configurations
lightweight_candidate:
  top_m: 15
  fasttext_model_path: "./models/fasttext_cpp.bin"
  faiss_index_path: "./models/faiss_cpp.index"
  faiss_vocab_path: "./models/vocab_cpp.json"

heavyweight_candidate:
  top_k_mlm: 60
  top_n_keep: 50
  semantic_threshold: 0.2
  structural_semantic_threshold: 0.5
  context_ratio: 0.3
  preserve_style: true

# Attacker and Optimizer Configurations
irtg_attacker:
  top_k: 5

genetic_algorithm:
  pop_size: 40
  stagnation_threshold: 5
  mutation_rate_min: 0.1
  mutation_rate_max: 0.5
  elite_ratio: 0.25

# Other System Components
analyzer:
  lang: "cpp"
mlm_engine:
  model_name: "microsoft/codebert-base-mlm"
smoother:
  num_samples: 10
  variance_threshold: 0.05
  replace_prob: 0.5
  batch_size: 32